name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Login to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login \
            --username="${{ secrets.ALIYUN_DOCKER_USERNAME }}" \
            --password-stdin crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build Docker image
        run: docker build -t crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/cellox/cello:latest .

      - name: Push Docker image
        run: docker push crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/cellox/cello:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login --username="${{ secrets.ALIYUN_DOCKER_USERNAME }}" \
              --password="${{ secrets.ALIYUN_DOCKER_PASSWORD }}" \
              crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com

            docker pull crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/cellox/cello:latest

            docker ps -q --filter "name=cello" | grep -q . && docker stop cello || echo "Container cello is not running"
            docker ps -a -q --filter "name=cello" | grep -q . && docker rm cello || echo "Container cello does not exist"

            docker run -d --name cello -p 8080:8080 crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/cellox/cello:latest
