name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # 根据你的项目需求选择 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # 假设你有一个 build 脚本

      - name: Login to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username="${{ secrets.ALIYUN_DOCKER_USERNAME }}" --password-stdin crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com

      - name: Build Docker image
        run: docker build -t crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/jiang-go/jiang-go-nest:latest .

      - name: Push Docker image
        run: docker push crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/jiang-go/jiang-go-nest:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login --username="${{ secrets.ALIYUN_DOCKER_USERNAME }}" --password="${{ secrets.ALIYUN_DOCKER_PASSWORD }}" crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com
            docker pull crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/jiang-go/jiang-go-nest:latest
            docker ps -q --filter "name=jiang-go-nest" | grep -q . && docker stop jiang-go-nest || echo "Container jiang-go-nest is not running"
            docker ps -a -q --filter "name=jiang-go-nest" | grep -q . && docker rm jiang-go-nest || echo "Container jiang-go-nest does not exist"
            docker run -d --name jiang-go-nest -p 8080:8080 crpi-6u1ldnk9renneqhh.cn-shanghai.personal.cr.aliyuncs.com/jiang-go/jiang-go-nest:latest
